pub const APP_TITLE: &str = "NEST";
pub const APP_VERSION: &str = "0.0.1";
pub const APP_IDENTIFIER: &str = "com.example";
pub const APP_REUSE_INSTANCE: bool = true;
pub const APP_URLS: &[(&str, &str)] = &[("example", "https://example.com/")];
pub const MAILTO_URL_TEMPLATE: &str = "https://example.com/?mailto={}";
pub const WINDOW_WIDTH: f64 = 1280 as f64;
pub const WINDOW_HEIGHT: f64 = 720 as f64;
pub const WINDOW_RESIZABLE: bool = true;
pub const WINDOW_TITLE_BAR: bool = true;
pub const WINDOW_FULLSCREEN: bool = false;
pub const WINDOW_MAXIMIZED: bool = false;
pub const WINDOW_ALWAYS_ON_TOP: bool = false;
pub const WINDOW_CLOSE_TO_TRAY: bool = true;
pub const WINDOW_TRAY_MENU: bool = true;
pub const WEBVIEW_INCOGNITO: bool = true;
pub const ENABLE_DRAG_DROP: bool = true;
pub const ALLOW_NEW_WINDOWS: bool = true;
pub const INTERNAL_URL_PREFIXES: &[&str] = &[];
pub const INTERNAL_URL_REGEXES: &[&str] = &[];
pub const WEBVIEW_ARGS: &str = "--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection --disable-blink-features=AutomationControlled --enable-features=SharedArrayBuffer --enable-unsafe-webgpu --force-dark-mode";
